version: '3.6'
services:

### NGINX Server #########################################
    projector_nginx:
      container_name: projector_nginx
      build:
        context: .
        dockerfile: nginx/Dockerfile
      volumes:
          - ./templates:/etc/nginx/templates
          - ./nginx/projector_hw9.conf:/etc/nginx/conf.d/projector_hw9.conf
          - ./nginx_cache:/etc/nginx_cache
#          - ./nginx_log:/var/log/nginx/
      ports:
        - "8080:80"
      environment:
        - NGINX_HOST=projector.localhost
        - NGINX_PORT=80

      links:
        - projector_service
      networks:
        - default
      depends_on:
        - projector_service

### ELASTIC Server #########################################
    projector_es:
      container_name: projector_es
      build:
        context: .
        dockerfile: es/Dockerfile
      environment:
        - cluster.name=projector-search-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - '0.0.0.0:9200:9200'
      volumes:
        - es-data:/usr/share/elasticsearch/data
      networks:
        - default

    projector_kibana:
      container_name: projector_kibana
      image: docker.elastic.co/kibana/kibana:7.12.0
      environment:
        ELASTICSEARCH_HOSTS: "http://projector_es:9200"
      ports:
        - '0.0.0.0:5601:5601'
      networks:
        - default
      depends_on:
        - projector_es

    projector_service:
      container_name: projector_service
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "0.0.0.0:4888:4888"
      volumes:
        - .:/app/

      environment:
        ENV_NAME: local
        ES_CONNECTION_URL: "http://projector_es:9200"
        # app settings
        APP_HOST: 0.0.0.0
        APP_PORT: 4888
        LOG_LEVEL: DEBUG

      depends_on:
        - projector_es
      networks:
        - default

volumes:
  db-data:
  es-data:
  redis-data:
  influxdb_data:
  grafana_data:
